### ISSUE TITLE
TypeError: api.chainWebpack is not a function

### ISSUE THREAD

**Issue by deejiw** [ldiebold/quasar-ui-firebase#7]
After installing with `quasar ext add firebase` and run `quasar dev` the console gave back the error

```App • Running "firebase" Quasar App Extension...
/Users/tjiw/Downloads/core/node_modules/quasar-app-extension-firebase/src/index.js:42
    api.chainWebpack((chain) => {
        ^

TypeError: api.chainWebpack is not a function
    at module.exports (/Users/tjiw/Downloads/core/node_modules/quasar-app-extension-firebase/src/index.js:42:9)
    at Extension.run (/Users/tjiw/Downloads/core/node_modules/@quasar/app-vite/lib/app-extension/Extension.js:242:11)
    at ExtensionsRunner.registerExtensions (/Users/tjiw/Downloads/core/node_modules/@quasar/app-vite/lib/app-extension/extensions-runner.js:16:31)
    at goLive (/Users/tjiw/Downloads/core/node_modules/@quasar/app-vite/lib/cmd/dev.js:133:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.9.1
```

`quasar info`

```
Operating System - Darwin(21.6.0) - darwin/arm64
NodeJs - 18.9.1

Global packages
  NPM - 8.19.1
  yarn - Not installed
  @quasar/cli - 1.3.2
  @quasar/icongenie - Not installed
  cordova - Not installed

Important local packages
  quasar - 2.10.0 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record time
  @quasar/app-vite - 1.1.3 -- Quasar Framework App CLI with Vite
  @quasar/extras - 1.15.5 -- Quasar Framework fonts, icons and animations
  eslint-plugin-quasar - Not installed
  vue - 3.2.39 -- The progressive JavaScript framework for building modern web UI.
  vue-router - 4.1.5
  pinia - 2.0.22 -- Intuitive, type safe and flexible Store for Vue
  vuex - Not installed
  vite - 2.9.15 -- Native-ESM powered web dev build tool
  eslint - 8.24.0 -- An AST-based pattern checker for JavaScript.
  electron - Not installed
  electron-packager - Not installed
  electron-builder - Not installed
  register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
  @capacitor/core - Not installed
  @capacitor/cli - Not installed
  @capacitor/android - Not installed
  @capacitor/ios - Not installed

Quasar App Extensions
  quasar-app-extension-firebase - 1.0.0-alpha.11 -- Simple firebase integration with the Quasar Framework
 ```

**Comment by deejiw** [comment]
Replaced with `quasar ext add @vueauth/auth`
