### ISSUE TITLE
Vite compatibility (Error: api.chainWebpack is not a function)?

### ISSUE THREAD

**Issue by BradDuns** [ldiebold/quasar-ui-firebase#8]
I tried installing with `quasar ext add firebase` and it seems to install ok but when I try to load the dev server I get an error:

```
App • Running "firebase" Quasar App Extension...
/PROJECT/node_modules/quasar-app-extension-firebase/src/index.js:42
    api.chainWebpack((chain) => {
        ^

TypeError: api.chainWebpack is not a function
    at module.exports (/PROJECT/node_modules/quasar-app-extension-firebase/src/index.js:42:9)
    at Extension.run (/PROJECT/node_modules/@quasar/app-vite/lib/app-extension/Extension.js:242:11)
    at ExtensionsRunner.registerExtensions (/PROJECT/node_modules/@quasar/app-vite/lib/app-extension/extensions-runner.js:16:31)
    at goLive (/PROJECT/node_modules/@quasar/app-vite/lib/cmd/dev.js:133:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
```

Is this because I am trying to use Vite instead of Webpack?

**Comment by TimAlber** [comment]
I am having the same exact issue.
Does anybody have a fix?

**Comment by BradDuns** [comment]
I don't exactly remember but I think I ended up installing firebase manually. 
I have it working in a project and it's not an extension.
I have Firebase CLI on my system (Don't know if that matters)
I did `yarn add firebase` in the project folder
I added firebase to `quasar.config.js`
```
boot: [
      'firebase',
    ],
```

then I added a firebase.js to `src/boot/`
```
import { boot } from 'quasar/wrappers'
import { initializeApp } from 'firebase/app'
import { getFirestore, collection } from 'firebase/firestore'

const firebaseConfig = {
  apiKey: 'XXX',
  authDomain: 'XXX',
  projectId: 'XXX',
  storageBucket: 'XXX',
  messagingSenderId: 'XXX',
  appId: 'XXX',
  measurementId: 'XXX',
}

// Initialize Firebase
export const firebaseApp = initializeApp(firebaseConfig)

// used for the firestore refs
export const db = getFirestore(firebaseApp)

export default ({ app, router, store }) => {}
```

It seems to be working for me. I added vuefire the same way.

**Comment by Nicolasaza** [comment]
```
 App •  WAIT  • Compiling of "UI" in progress...
 App •  DONE  • "UI" compiled with errors • 10158ms



 App •  ERROR  •  UI  Reported by ESLint:
[eslint] 
/Users/nicolas/Desktop/TEST FIRE/quasar-project/config/firebase-config.js
  3:13  error  Strings must use singlequote  quotes
  4:17  error  Strings must use singlequote  quotes
  5:18  error  Strings must use singlequote  quotes
  6:16  error  Strings must use singlequote  quotes
  7:20  error  Strings must use singlequote  quotes
  8:24  error  Strings must use singlequote  quotes
  9:12  error  Strings must use singlequote  quotes

/Users/nicolas/Desktop/TEST FIRE/quasar-project/src/actions/firebase/useRegister.js
  1:10  error  useEmailRegister not found in 'firebase-composables'  import/named

/Users/nicolas/Desktop/TEST FIRE/quasar-project/src/actions/firebase/useSignIn.js
  2:10  error  useEmailSignIn not found in 'firebase-composables'  import/named

✖ 9 problems (9 errors, 0 warnings)
  7 errors and 0 warnings potentially fixable with the `--fix` option.

You may use special comments to disable some warnings:
 · // eslint-disable-next-line to ignore the next line.
 · /* eslint-disable */ to ignore all warnings in a file.



 App •  COMPILATION FAILED  • Please check the log above for details.

```
